### ISSUE TITLE
Refactor Filter.freq setter to use non-linear function

### ISSUE THREAD

**Issue by jsakas** [jsakas/Subtractor#17]
Some of the terminology here might be wrong but I'll try to explain it as best as I can.

We should abstract the setFreq function so that it is not actually expecting an exact frequency, but an abstract value from 1-127. This value then gets converted to a frequency by a non-linear function. 

Our ears discern changes in cut off much more precise in the lower frequency range, so the current implementation doesn't give you much actual filtering effect until the knob is 1/3 of the way down. 

The simplest form of this function would just be `x^2` where x is the knob value, but this doesn't get you all the way to the highest frequency value of 22050, since `127^2 = 16129`... However, if we make the knob maximm from 149 instead of 127, x^2 gets us the full frequency spectrum we are looking for so that much be an option as well.

**Comment by jsakas** [comment]
Update: The value is already abstracted, but it still needs to use a non-linear function

**Comment by stealthybox** [comment]
I believe we just need to use the midi calculation function already in our code base.
