### ISSUE TITLE
Normalize the output level of polyphony

### ISSUE THREAD

**Issue by andrewhannum** [jsakas/Subtractor#24]
Currently as more voices play together (either polyphony, or playing simultaneous notes as in chords) the waveforms sum their magnitudes and usually immediately exceed the 1.0 threshold of the final destination output. This causes clipping at least visually (in the oscilloscope) and possibly audibly (not sure about this).

This might not necessarily be a problem, if this is the intended functionality (chords louder than single notes, multiple voices louder than single voices), but there should at least be a way to manually control final output gain, if not a way of automatically reducing the combined output when adding additional voices (averaging instead of summing?).

**Comment by jsakas** [comment]
I think this can be accomplished by https://github.com/jsakas/Subtractor/issues/29
