### ISSUE TITLE
Add piano keys below oscilloscope

### ISSUE THREAD

**Issue by jsakas** [jsakas/Subtractor#27]
I think it would be cool if we had some piano keys that show up below the oscilloscope, which will be a visual indicator of which keys you are playing. 

![piano_keys](https://user-images.githubusercontent.com/4934432/30776934-d914c312-a06c-11e7-96c7-6876f71f3db0.gif)

Likely the best way to do this is probably with a canvas element. Here is how I think it could be implemented:

- Create `Keyscope` class, which operates similar to Oscilloscope in using `requestAnimationFrame` to constantly be redrawing
- Write a function to dynamically draw a keyboard, with options for start key, number of octaves, etc. The function should be "responsive" in that it will space out the keys automatically based on the available space. Keys could ultimately be very fat or skinny depending on where its drawn and how many keys we decide to display. 
- In the Subtractor class, we need to keep an array of all of the currently pressed key notes. This will be useful for other things in the future as well
- As part of the drawing process in `Keyscope`, keys that are pressed in the Subtractor are highlighted in some way.

**Comment by jsakas** [comment]
@andrewhannum maybe?

**Comment by stealthybox** [comment]
I'm going to try this with an SVG in a web component. 🎹

**Comment by stealthybox** [comment]
see pull #35 for an SVG implementation

**Comment by jsakas** [comment]
Closed by https://github.com/jsakas/Subtractor/pull/35
