### ISSUE TITLE
Host static site of master branch

### ISSUE THREAD

**Issue by stealthybox** [jsakas/Subtractor#40]
Now that we have #34, we can use CI to webpack and publish to [gh-pages](https://pages.github.com/).

**Comment by jsakas** [comment]
Note: website folder should replace demo folder

**Comment by stealthybox** [comment]
I don't see a `gh-pages` branch.
Is this closed?
What's the URL?

**Comment by stealthybox** [comment]
Still confused why I can't see the branch, but this link works:
https://jsakas.github.io/Subtractor/

**Comment by jsakas** [comment]
It is served out of the docs folder which is the other option. It was a quick way to do it by replacing `demo` with `docs` and building css / js to that folder. One issue already is that the compiled css / js is part of SCM - but I just wanted to get a quick static site up.

**Comment by stealthybox** [comment]
ah makes sense -- we can look at changing that in the future if necessary.
