### ISSUE TITLE
Refactor presets to be more maintanable

### ISSUE THREAD

**Issue by jsakas** [jsakas/Subtractor#52]
Requirements:

- Presets missing a value should not show NaN for that value but use the default
- Write preset converter that takes old presets and updates them to include possible missing values
- Preset obj should match Subtractor object we can do something like `Object.assign(this, presetObj)`

**Comment by stealthybox** [comment]
> Write preset converter that takes old presets and updates them to include possible missing values

Do you just mean the function that sets the defaults.
I don't see a need to write any user-facing interface for this.
